# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{theaboutbox-foreigner}
  s.version = "0.7.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ho-Sheng Hsiao"]
  s.date = %q{2010-07-23}
  s.description = %q{Allows you to add foreign keys to your migrations and enforce them. Forked to fix exception on Rails 3 beta 4}
  s.email = %q{hosh@sparkfly.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "lib/foreigner.rb",
     "lib/foreigner/connection_adapters/abstract/schema_definitions.rb",
     "lib/foreigner/connection_adapters/abstract/schema_statements.rb",
     "lib/foreigner/connection_adapters/mysql_adapter.rb",
     "lib/foreigner/connection_adapters/postgresql_adapter.rb",
     "lib/foreigner/connection_adapters/sqlite3_adapter.rb",
     "lib/foreigner/schema_dumper.rb",
     "lib/foreigner/semantics/sql_2003.rb",
     "spec/adapter_helper.rb",
     "spec/factory_helper.rb",
     "spec/mysql/schema_extractor_spec.rb",
     "spec/mysql/schema_spec.rb",
     "spec/mysql/semantics_spec.rb",
     "spec/postgresql/schema_extractor_spec.rb",
     "spec/postgresql/schema_spec.rb",
     "spec/postgresql/semantics_spec.rb",
     "spec/schema_dumper_spec.rb",
     "spec/spec_helper.rb",
     "spec/sqlite3/schema_spec.rb",
     "tasks/foreigner_tasks.rake"
  ]
  s.homepage = %q{http://github.com/theaboutbox/foreigner}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Foreign keys for Rails migrations for PostgreSQL, MySQL and Sqlite3. Based on dwilkie-foreigner}
  s.test_files = [
    "spec/adapter_helper.rb",
     "spec/factory_helper.rb",
     "spec/mysql/schema_extractor_spec.rb",
     "spec/mysql/schema_spec.rb",
     "spec/mysql/semantics_spec.rb",
     "spec/postgresql/schema_extractor_spec.rb",
     "spec/postgresql/schema_spec.rb",
     "spec/postgresql/semantics_spec.rb",
     "spec/schema_dumper_spec.rb",
     "spec/spec_helper.rb",
     "spec/sqlite3/schema_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

